### ISSUE TITLE
Link to github use wrong url

### ISSUE THREAD

**Issue by mtorromeo** [cockpit-project/cockpit-weblate#1]
In the weblate interface there are useful links that should open the source code pointing to the position of the original strings on github, but the links are in the form

https://github.com/cockpit/cockpit/blob/master/pkg/machines/components/diskAdd.jsx#L242

while they should be like this (cockpit-project instead of just cockpit)

https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/components/diskAdd.jsx#L242

**Comment by marusak** [comment]
Sorry about that. It was wrong configuration in Weblate. Fixed.
